import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-cargo-loss-damage-claims-recovery",
  "engine": "recovery",
  "title": "Cargo Loss & Damage Claims Recovery",
  "shortTitle": "Cargo Claims Recovery",
  "tagline": "Prove custody, condition, liability, value, and deadlines for every cargo claim",
  "industry": "Multimodal Cargo Claims",
  "uiPort": 4580,
  "apiPort": 5580,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Lost, short, damaged, or temperature-compromised shipment value recovered from accountable parties",
  "valueNarrative": "Reconstruct shipment custody with bills of lading, scans, seals, photos, temperature data, surveys, invoices, liability terms, and settlements.",
  "calculation": {
    "actualKey": "settledClaim",
    "expectedKey": "eligibleClaim",
    "actualLabel": "Carrier or Insurer Settlement",
    "expectedLabel": "Supported Cargo Claim",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Custody, condition, invoice, and carrier liability evidence indicate unrecovered cargo loss.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("carrier-liability-library","CCR01","Carrier liability library","Reconcile carrier liability library using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed carrier liability library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Carrier liability library Reference","text","CCR01-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("shipment-commodity-registry","CCR02","Shipment commodity registry","Reconcile shipment commodity registry using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed shipment commodity registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Shipment commodity registry Reference","text","CCR02-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("bill-of-lading-ingestion","CCR03","Bill-of-lading ingestion","Reconcile bill-of-lading ingestion using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed bill-of-lading ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Bill-of-lading ingestion Reference","text","CCR03-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("custody-event-timeline","CCR04","Custody event timeline","Reconcile custody event timeline using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed custody event timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Custody event timeline Reference","text","CCR04-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("seal-and-handoff-tracking","CCR05","Seal and handoff tracking","Reconcile seal and handoff tracking using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed seal and handoff tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Seal and handoff tracking Reference","text","CCR05-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("shortage-detection","CCR06","Shortage detection","Reconcile shortage detection using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed shortage detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Shortage detection Reference","text","CCR06-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("damage-photo-and-survey-evidence","CCR07","Damage photo and survey evidence","Reconcile damage photo and survey evidence using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed damage photo and survey evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Damage photo and survey evidence Reference","text","CCR07-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("temperature-excursion-analysis","CCR08","Temperature excursion analysis","Reconcile temperature excursion analysis using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed temperature excursion analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Temperature excursion analysis Reference","text","CCR08-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("salvage-value-management","CCR09","Salvage value management","Reconcile salvage value management using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed salvage value management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Salvage value management Reference","text","CCR09-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("replacement-cost-calculation","CCR10","Replacement-cost calculation","Reconcile replacement-cost calculation using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed replacement-cost calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Replacement-cost calculation Reference","text","CCR10-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("liability-limitation-calculation","CCR11","Liability limitation calculation","Reconcile liability limitation calculation using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed liability limitation calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Liability limitation calculation Reference","text","CCR11-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("claim-filing-deadline-control","CCR12","Claim filing deadline control","Reconcile claim filing deadline control using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed claim filing deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Claim filing deadline control Reference","text","CCR12-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("claim-packet-generation","CCR13","Claim packet generation","Reconcile claim packet generation using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed claim packet generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Claim packet generation Reference","text","CCR13-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("carrier-response-workflow","CCR14","Carrier response workflow","Reconcile carrier response workflow using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed carrier response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Carrier response workflow Reference","text","CCR14-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("settlement-reconciliation","CCR15","Settlement reconciliation","Reconcile settlement reconciliation using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Settlement reconciliation Reference","text","CCR15-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]}),
feature("carrier-commodity-and-lane-analytics","CCR16","Carrier commodity and lane analytics","Reconcile carrier commodity and lane analytics using carrier contracts, bills of lading, shipment events, custody scans, seals, delivery exceptions, photos, surveys, temperature telemetry, replacement costs, salvage, and liability rules.","Produce a governed carrier commodity and lane analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrierShipment","Carrier / Shipment","text","Northstar Freight / BOL-884120"],["caseReference","Carrier commodity and lane analytics Reference","text","CCR16-2026-001"],["settledClaim","Carrier or Insurer Settlement","currency",425000],["eligibleClaim","Supported Cargo Claim","currency",612000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledClaim",subjects:["Temperature excursion","In-transit damage","Cargo shortage","Total shipment loss","Concealed damage"]})
]);
